name: "Coding Standards"
on:
  workflow_dispatch: null
permissions:
  contents: "write"
  pull-requests: "write"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  fix:
    name: "Fix"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v4"
    - name: "Install PHPCS"
      run: |
        composer require --no-plugins --dev wp-coding-standards/wpcs
        composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        composer run post-install-cmd
    - name: "Fix violations"
      run: |
        # phpcbf exists with 1 on success
        vendor/bin/phpcbf --standard=WordPress-Core *.php includes/ || true
        # Complex errors need a second run
        vendor/bin/phpcbf --standard=WordPress-Core *.php includes/ || true
    - name: "Check difference to repository"
      id: "list_diff"
      run: |
        if ! git diff --exit-code; then
          echo "exit_status=1" >>"${GITHUB_OUTPUT}"
        fi
    - name: "Create pull request"
      if: "${{ steps.list_diff.outputs.exit_status == '1' }}"
      uses: "peter-evans/create-pull-request@v4"
      with:
        add-paths: |
          *.php
          includes/
        branch: "cs-fixer"
        commit-message: "Fix CS"
        title: "Fix Coding Standards violations"
        body: |
            Automated changes by running `phpcbf`.
        delete-branch: true
