name: "Integrate"

on:
  pull_request: null
  push:
    branches:
      - "stable"

jobs:
  syntax-check:
    name: "Syntax check on all PHP versions"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-versions: [5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: ${{ matrix.php-versions }}
    - name: "PHP lint"
      run: "find *.php includes/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l"

  coding-standard:
    name: "Check coding standard"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "7.3"
    - name: "Install PHPCS"
      run: "composer require --dev wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer"
    - name: "Run PHPCS"
      run: "vendor/bin/phpcs --standard=WordPress-Core *.php includes/"

  static-analysis:
    name: "Run static analysis"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "7.3"
    - name: "Install PHPStan"
      run: "composer require --dev szepeviktor/phpstan-wordpress"
    - name: "Run PHPStan"
      run: "vendor/bin/phpstan analyze"
